version: "3.8"
services:
  app:
    build: ./app
    restart: always
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
