INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (1, 'TSH w/reflex to T4 Free', 0.45, 4.5, 'mIU/L', 4.3512);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (3, 'T3 Total', 1.155, 3.388, 'mmol/L', 3.4734);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (5, 'T4 Total', 0.069, 0.185, 'mmol/L', 0.30157);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (7, 'WBC', 4.0, 10.0, '10e9/L', 86.216);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (9, 'Hemoglobin', 13.7, 17.5, 'g/dL', 645.8);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (11, 'MCV', 80.0, 100.0, 'fL', 139.95);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (13, 'MCHC', 320.0, 360.0, 'g/L', 1375.7);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (15, 'Platelet Count', 163.0, 369.0, '10e9/L', 364.29);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (17, 'Neutrophil %', 34.0, 71.0, '%', 164.81);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (19, 'Monocyte %', 5.0, 12.0, '%', 10.286);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (21, 'Basophil %', 0.4, 1.0, '%', 2.4216);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (23, 'Neutrophil Absolute', 1.8, 7.7, '10e9/L', 7.3037);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (25, 'Monocyte Absolute', 0.24, 0.82, '10e9/L', 0.71417);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (27, 'Basophil Absolute', 0.01, 0.08, '10e9/L', 1.0819);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (29, 'Protime/INR', 11.0, 13.5, 'seconds', 15.809);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (31, 'Reticulocyte Count', 0.5, 1.5, '%', 8.4873);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (33, 'Morphology', -1.0, -1.0, 'mIU/L', -1.0658);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (35, 'Poikilocytosis', 0.0, 0.0, '', 0.0);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (37, 'Ovalocytes', 0.0, 0.0, '', 0.0);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (39, 'Schistocytes/OPF', 0.0, 0.0, '', 0.0);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (41, 'RBC Morphology', 0.0, 0.0, '', 0.0);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (42, 'Hypersegmented neutrophils', 0.0, 0.0, '', 0.0);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (43, 'Blood Gases (ABG)', -1.0, -1.0, 'mIU/L', -6.6884);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (45, 'pH - arterial blood', 7.34, 7.44, 'unitless', 13.549);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (47, 'pCO2 (partial pressures of carbon dioxide)', 269.15, 346.05, 'Kpa', 641.74);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (51, 'Fibrinogen', 150.0, 350.0, '', 830.33);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (53, 'Amylase', 0.377, 1.394, 'mckat/L', 0.96005);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (55, 'Direct Bilirubin', 0.0, 3.42, 'umol/L', 9.4292);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (57, 'BUN', 2.142, 8.211, 'mmol/L', 5.4278);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (59, 'CEA', 0.0, 2.5, 'µg/L', 1.7108);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (61, 'Creatinine', 61.88, 114.92, 'umol/L', 1009.1);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (63, 'Estradiol', 91.775, 2202.6, 'pmol/L', 1775.5);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (65, 'Folic Acid (in red cell)', 360.0, 1400.0, 'nmol/L', 1079.7);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (67, 'Follicle Stimulating Hormone (FSH)', 0.197, 0.935, 'mckat/L', 0.88088);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (69, 'Glucose', 3.575, 5.445, 'mmol/L', 20.401);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (71, 'Glucose 2hr Post Prandial', 4.95, 7.7, 'mmol/L', 8.2);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (73, 'Glucose Tolerance 3hr (75g)', 4.95, 7.7, 'mmol/L', 7.5648);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (75, 'HGB (Hemoglobin) A1C', 4.0, 7.0, '%', 13.772);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (77, 'Hemoglobinopathy Profile', 0.0, 1.0, '', 0.68175);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (79, 'Hepatitis A Ab', 0.0, 1.0, '', 1.849);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (81, 'Hepatitis B Surface Ag', 0.0, 1.0, '', 0.66261);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (83, 'Hepatitis B Core Ab, IgM', 0.0, 1.0, '', 1.7821);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (85, 'Herpes Type 1/2 IgG/IgM', 0.0, 1.0, '', 1.0853);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (87, 'Herpes Type 2 Glyco IgG', 0.0, 1.0, '', 1.339);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (89, 'High Sensitive CRP', 1.0, 3.0, 'mg/L', 7.3942);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (91, 'Iron, Serum', 8.95, 30.43, 'umol/L', 183.67);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (93, 'Iron (Transferrin)', 36.516, 64.44, 'umol/L', 96.105);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (95, 'Lead Venous', 0.0, 0.483, 'umol/L', 3.1826);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (97, 'Luteinizing Hormone', 0.016, 0.328, 'mckat/L', 0.31271);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (99, 'Measles Ab (Rubeola) IgG', 0.0, 1.0, '', 0.54933);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (101, 'Potassium', 3.5, 5.1, 'mmol/L', 13.033);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (103, 'Protein EP (Electrophoresis) and Total', -1.0, -1.0, 'mIU/L', -3.6133);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (105, 'Albumin', 35.0, 57.0, 'g/L', 54.849);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (107, 'Alpha2-globulin', 6.0, 10.0, 'g/L', 23.681);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (109, 'Gamma-globulin', 7.0, 16.0, 'g/L', 11.733);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (111, 'PSA Diag ICD-9', 2.5, 4.0, 'µg/L', 35.111);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (113, 'Rheumatoid Factor, units', 14.0, 60.0, 'U/mL', 66.461);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (115, 'Rubella Ab - IgG', 0.0, 1.0, '', 1.0203);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (117, 'Varicella Zoster Ab IgG', 0.0, 1.0, '', 0.5064);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (119, 'Vitamin D, 25 Hydroxy', 74.88, 184.704, 'nmol/L', 309.66);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (121, 'eGFR for African Americans', 1.5, 2.0, 'mL/sec', 6.6986);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (123, 'Troponin', 0.0, 0.05, 'ng/mL', 0.030716);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (124, 'IgE Total, Immunoglobulin', 0.0, 380.0, 'IU/mL', 348.11);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (125, 'IGF-1 Insulin-like Growth Factor-1', 117.0, 771.0, 'ng/mL', 1098.0);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (127, 'BNP (B-type natriuretic peptide)', 15.0, 100.0, '', 62.367);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (128, 'Hepatitis A Ab, IgM', 0.0, 1.0, '', 2.5822);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (129, 'Hepatitis B Core Ab, IgM', 0.0, 1.0, '', 0.5075);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (130, 'Hepatitis B Surface Ag', 0.0, 1.0, '', 1.0127);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (132, 'ABO grouping', 0.0, 0.0, '', 0.0);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (134, 'Ab (Antibody) Screen', 0.0, 1.0, '', 0.64979);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (136, 'Rubella Ab - IgG', 0.0, 1.0, '', 0.68082);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (137, 'Hepatitis B Surface Ag', 0.0, 1.0, '', 0.69786);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (138, 'Creatinine', 61.88, 114.92, 'umol/L', 330.14);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (139, 'Bicarbonate (CO2)', 22.0, 32.0, 'mmol/L', 89.024);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (141, 'Potassium', 3.5, 5.1, 'mmol/L', 6.2912);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (142, 'Sodium', 135.0, 145.0, 'mmol/L', 178.42);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (143, 'BUN', 2.142, 8.211, 'mmol/L', 6.9142);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (144, 'Glucose', 3.575, 5.445, 'mmol/L', 11.009);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (146, 'Osmolality (serum)', 280.0, 300.0, 'mmol/kg', 455.75);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (147, 'Bicarbonate (CO2)', 22.0, 32.0, 'mmol/L', 70.543);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (149, 'Potassium', 3.5, 5.1, 'mmol/L', 15.884);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (150, 'Sodium', 135.0, 145.0, 'mmol/L', 234.19);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (152, 'Alkaline Phosphatase (ALP)', 0.656, 2.116, 'mckat/L', 1.4074);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (157, 'Creatinine', 61.88, 114.92, 'umol/L', 315.75);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (158, 'Glucose', 3.575, 5.445, 'mmol/L', 4.7226);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (159, 'Potassium', 3.5, 5.1, 'mmol/L', 7.1533);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (160, 'Sodium', 135.0, 145.0, 'mmol/L', 645.34);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (162, 'BUN', 2.142, 8.211, 'mmol/L', 146.54);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (163, 'Bicarbonate (CO2)', 22.0, 32.0, 'mmol/L', 44.49);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (168, 'Alkaline Phosphatase', 0.656, 2.116, 'mckat/L', 1.4703);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (170, 'Direct Bilirubin', 0.0, 3.42, 'umol/L', 5.8489);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (175, 'HDL', 1.295, 1.528, 'mmol/L', 6.122);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (179, 'HDL', 1.295, 1.528, 'mmol/L', 2.5674);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (181, 'DLDL', 2.59, 3.367, 'mmol/L', 14.077);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (183, 'Apo B (Apolipoprotein B)', 0.13, 2.0, 'g/L', 4.1317);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (185, 'Homocysteine', 5.0, 15.0, 'mmol/L', 16.298);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (189, 'Bicarbonate (CO2)', 22.0, 32.0, 'mmol/L', 200.58);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (191, 'Creatinine', 61.88, 114.92, 'umol/L', 988.74);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (192, 'Glucose', 3.575, 5.445, 'mmol/L', 10.91);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (194, 'Potassium', 3.5, 5.1, 'mmol/L', 4.7805);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (195, 'Sodium', 135.0, 145.0, 'mmol/L', 247.5);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (196, 'BUN', 2.142, 8.211, 'mmol/L', 5.9585);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (197, 'GC/Chlamydia NAAT', 0.0, 1.0, '', 0.66288);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (199, 'Group B Strep Penicillin Allergic', 0.0, 1.0, '', 0.53276);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (201, 'Wet Mount (Trichomonas)', 0.0, 1.0, '', 0.53798);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (203, 'Anaerobic/Aerobic Culture (Abscess/Tissue/Fluid only)', 0.0, 1.0, '', 0.54569);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (205, 'Respiratory (Sputum) Culture', 0.0, 1.0, '', 5.4008);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (207, 'Throat Culture', 0.0, 1.0, '', 2.5545);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (209, 'MRSA Culture (Nasal/skin only)', 0.0, 1.0, '', 2.0583);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (211, 'Stool Culture', 0.0, 1.0, '', 0.62499);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (213, 'Ova & Parasite Exam', 0.0, 1.0, '', 0.76115);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (215, 'Helicobacter pylori Stool Antigen', 0.0, 1.0, '', 0.64954);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (217, 'AFB (Mycobacteria) Culture', 0.0, 1.0, '', 0.59384);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (219, 'Fungal Culture (Skin/Hair/Nails)', 0.0, 1.0, '', 5.0759);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (221, 'RSV (Respiratory Virus) NAAT', 0.0, 1.0, '', 1.3873);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (223, 'Varicella Rapid Culture', 0.0, 1.0, '', 1.0438);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (225, 'Urine Culture', 0.0, 1.0, '', 0.82262);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (227, 'Mononucleosis spot test', 0.0, 1.0, '', 0.50207);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (229, 'Screen Low Risk Pap ICD-9', 0.0, 0.0, '', 0.0);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (231, 'Diagnostic Pap ICD-9', 0.0, 0.0, '', 0.0);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (233, 'HPV if ASCUS (HPV ASCUS)', 0.0, 1.0, '', 6.412);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (235, 'HPV Only - No Pap (HPV AUTO)', 0.0, 1.0, '', 0.54789);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (240, 'Rheumatoid Factor, units', 14.0, 60.0, 'U/mL', 87.052);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (241, 'C-Reactive Protein (CRP)', 0.0, 5.0, 'mg/L', 4.3062);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (243, 'Antibody Screen', 0.0, 1.0, '', 0.62819);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (244, 'AlphaFeto Protein (AFP)', 10.0, 150.0, 'ug/L', 108.67);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (245, 'AFP (AlphaFeto Protein)', 10.0, 150.0, 'ug/L', 129.02);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (248, 'Dimeric inhibin A (DIA)', 40.0, 700.0, '', 463.5);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (250, 'Color (URINE TEST)', 0.0, 0.0, '', 0.0);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (252, 'Bilirubin (URINE TEST)', 0.0, 1.0, '', 1.13);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (254, 'Specific Gravity Urine', 1005.0, 1030.0, 'kg/m3', 2549.8);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (256, 'pH Urine', 4.5, 8.0, 'unitless', 29.978);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (258, 'Urobilinogen (URINE TEST)', 1.7, 34.0, 'umol/L', 35.429);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (260, 'Leukocyte Esterase (URINE TEST)', 0.0, 0.0, '', 0.0);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (262, 'RBC (erythrocytes) (URINE TEST)', 0.0, 2.0, 'hpf', 1.4206);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (264, 'Bacteria (URINE TEST)', 0.0, 0.0, '', 0.0);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (266, 'Sodium (Na) (URINE TEST)', 150.0, 300.0, 'mmol/24hrs', 238.62);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (268, 'Calcium (Ca) (URINE TEST)', 2.5, 8.0, 'mmol/24hrs', 5.9571);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (270, 'Creatinine (URINE TEST)', 4.8, 19.0, 'mmol/24hrs', 15.557);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (272, 'Urinalysis Reflex Comment', 0.0, 0.0, '', 0.0);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (274, 'Urine Culture', 0.0, 1.0, '', 0.51688);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (276, 'Sweat chloride', 0.0, 1.0, '', 0.65418);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (278, 'Stool trypsin and chymotrypsin', 0.0, 1.0, '', 0.56785);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (280, 'Glucose', 3.575, 5.445, 'mmol/L', 23.783);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (281, 'Insulin', 6.0, 27.0, 'mIU/L', 22.658);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (286, 'Mercury', 0.0, 39.92, 'nmol/L', 32.95);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (287, 'Iron, Serum', 8.95, 30.43, 'umol/L', 60.774);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (289, 'Zinc Protoporphyrin', 9.18, 16.83, 'umol/L', 136.53);
INSERT INTO Teste (Cod_Anal, Procedimento, Valor_Min, Valor_Max, Unidades, Resultado) VALUES (290, 'Rubella Ab - IgG', 0.0, 1.0, '', 1.1651);
